#!/bin/sh

function check_new_capi_appfw()
{
    NEW_CAPI_TEST_SRC="/tmp/new_capi_test.cpp"
    NEW_CAPI_TEST_OBJ="/tmp/new_capi_test.o"
    INCLUDES="-I/usr/include/appfw"

    cat << EOF > ${NEW_CAPI_TEST_SRC}
#include <app.h>

int main(int argc, char *argv[])
{
    service_h __attribute__((unused)) handle;

    return 0;
}
EOF

    if gcc ${INCLUDES} -c ${NEW_CAPI_TEST_SRC} -o ${NEW_CAPI_TEST_OBJ}; then
        echo "/* PRIVATE_CAPI_APPFW config not set */"
    else
        echo "#define PRIVATE_CAPI_APPFW"
    fi

    rm -f ${NEW_CAPI_TEST_SRC} ${NEW_CAPI_TEST_OBJ} 2>&1 > /dev/null
}

NEW_CAPI_APPFW=$(check_new_capi_appfw)

API_CONFIG_DEFINES="
${NEW_CAPI_APPFW}
"

cat << EOF
/*
 * Autogenerated header
 */

#ifndef __API_CONFIG__
#define __API_CONFIG__
${API_CONFIG_DEFINES}
#endif /* __API_CONFIG__ */
EOF
